http://localhost:4004/structured-types/Divers
?$expand=equipmentToOne,equipmentToMany
# -> works, nested entity + entities get expanded inline
###
http://localhost:4004/structured-types/Divers
?$expand=equipmentToMany($filter=suite_formfactor eq 'kid')
# -> works, only shows those divers who have a suite 
# with formfactor 'kid'
###
http://localhost:4004/structured-types/Divers
?$expand=equipmentToOne($filter=suite_formfactor eq 'kid')
# -> fails
# same query as above, only on a nested structure
# instead of entity set
###

http://localhost:4004/structured-types/Divers
?$expand=equipmentToOne
&$filter=equipmentToOne/suite_formfactor eq 'kid'
# -> fails
# trying with different query syntax